config/routes.rb
Rails.application.routes.draw do

  get 'welcome/login'
  get 'sessions/new'
  get 'customers/login'


  post 'sessions/create'

  get 'sessions/destroy'

  root 'welcome#index'

  get 'allhaps' => 'happenings#allhaps'

  resources :businesses do
    resources :happenings
  end
  resources :customers



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :set_business, except: [:index, :new, :create]

  def index

  end

  def show
    # @business = Business.find_by(id: session[:business_id])
  end



  def new
    @business = Business.new

    if request.xhr?
     render :partial => "form", :layout => false
    end
  end

  def create
    @business = Business.new(business_params)
    if @business.save
      session[:business_id] = @business.id
      redirect_to business_url(@business), :notice => "Signed up!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    p params
    if @business.update_attributes(business_params)
      redirect_to @business
    else
      render :edit
    end
  end

  def destroy
    @business.destroy

    redirect_to root_url
  end

  private
    def business_params
      params.permit(:name, :address, :city, :state, :zip, :password, :twitterDisplayName, :twitterUid, :twitterProfile_image_url, :twitterUsername)
    end

    def partial

    if request.xhr?
      if request[:partion => 'create']
        render :partial => "partials/createDealsForm", :layout => false
      elsif request[:partion => 'ongoing']
        render :partial => "partials/ongoingDeals", :layout => false
      elsif request[:partion => 'save']
        rener :partial => "partials/reuseableDeals", :layout=> false
      end
    end
  end

    def set_business
      @business = Business.find(params[:id])
    end

    # def customer_params
    #   params.require(:customer).permit(:email, :password)
    # end
end

app/views/businesses/_form.html.erb
<div class="bForm">
<%= form_for @business do |f| %>
  <div class="form-div">
    <%= f.label :name, :class => "splashFont" %><br>
    <%= f.text_field :name, id: 'name_input' %>
  </div>

  <div class="form-div">
    <%= f.label :address, :class => "splashFont" %><br>
    <%= f.text_field :address, id: 'address_input' %>
  </div>

  <div class="form-div">
    <%= f.label :city, :class => "splashFont" %><br>
    <%= f.text_field :city, id: 'city_input' %>
  </div>

  <div class="form-div">
    <%= f.label :state, :class => "splashFont" %><br>
    <%= f.text_field :state, id: 'state_input' %>
  </div>

  <div class="form-div">
    <%= f.label :zip, :class => "splashFont" %><br>
    <%= f.text_field :zip, id: 'zip_input' %>
  </div>

  <div class="form-div">
    <%= f.label :password, :class => "splashFont" %><br>
    <%= f.tpassword_field :password, id: 'password_input' %>
  </div>
  <br>
  <div class="form_div">
    <%= f.submit "Submit", id: 'new_bus', :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'%>
    <button class='mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent backButton'>Back</button>
  </div>

<% end %>
</div>

app/views/businesses/_login.html.erb
<%= form_for @business, {url: sessions_create_path } do |f| %>
  <div class="form-div">
    <%= f.label :email, :class => "splashFont" %><br>
    <%= f.text_field :email, id: 'email_input' %>
  </div>

  <div class="form-div">
    <%= f.label :password, :class => "splashFont"  %><br>
    <%= f.password_field :password, id: 'password_input' %>
  </div>
  <%= f.hidden_field :is_business, :value => true %>
  <br>
  <div class="form_div">
    <%= f.submit "Submit", :class => 'busSubmittButton mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
    <button class='mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent backButton'>Back</button>
  </div>

<% end %>

app/views/businesses/_show.html.erb
<div class="busDealsButton">
  <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" id="createHappeninButton">Create Happenin</button>
  <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" id="ongoingHappingButton">Ongoing Happenin</button>
  <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" id="saveHappeninButton">Save Happenin</button>
</div>
<div class="busShowContainer">

</div>

app/views/businesses/edit.html.erb
<div class="container">
  <h2>Edit Business</h2>

  <%= render 'form' %>

</div>

app/views/businesses/new.html.erb
<div class="container">
  <h2>New Business</h2>

  <%= render 'form' %>

</div>

app/views/businesses/show.html.erb
<div class="container">
  <div class="mdl-grid nopadding">
    <div class="mdl-cell mdl-cell--4-col nomargin dashboard-header">
      <img class="dashboard-header-image" src="<%= @business.twitterProfile_image_url %>" />
    </div>

    <div class="mdl-cell mdl-cell--8-col nomargin dashboard-header">
      <%= hidden_field :business, :id %>
      <h2><%= @business.name %></h2>
      <p><%= @business.address %> <%= @business.city %> <%= @business.state %></p>
      <a href="#" id="edit-business-link">
        <i class="material-icons">create</i> edit business info
      </a>
    </div>

    <div class="mdl-cell mdl-cell--4-col nomargin">
      <button id ="facebookAuth" type="button"  class= "btn btn-default facebookAuth oauthButton">Connect using facebook</button>
      <button id ="twitterAuth" type="button"  class= "btn btn-default twitterAuth oauthButton">Connect using Twitter</button>
    </div>

    <div class="mdl-cell mdl-cell--4-col nomargin">
      <ul>
        <li>12321</li>
        <li>12321</li>
        <li>12321</li>
        <li>12321</li>
      </ul>
    </div>

    <div class="mdl-cell mdl-cell--4-col nomargin" id="edit-pane">
    </div>
  </div>
</div>